# Generated by Django 2.2.6 on 2019-11-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('href', models.URLField(max_length=2084)),
                ('date_published', models.DateField()),
            ],
        ),
    ]
