# Generated by Django 2.2.6 on 2019-11-17 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VideoRecomApp', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=1028, verbose_name='コメント'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VideoRecomApp.Movie', verbose_name='映画ID'),
        ),
    ]
