# Generated by Django 2.2.6 on 2019-11-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoRecomApp', '0005_auto_20191117_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
