# Generated by Django 2.2.6 on 2019-11-23 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VideoRecomApp', '0006_auto_20191123_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VideoRecomApp.Genre'),
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
