# Generated by Django 2.2.6 on 2019-11-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoRecomApp', '0007_auto_20191123_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='MovieGenre',
        ),
    ]
