# Generated by Django 2.2.6 on 2019-11-23 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('release_date', models.DateField()),
                ('summary', models.CharField(max_length=1028)),
                ('href', models.URLField(max_length=2084)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VideoRecomApp.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1028, verbose_name='コメント')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VideoRecomApp.Movie', verbose_name='映画ID')),
                ('tag', models.ManyToManyField(blank=True, to='VideoRecomApp.Tag', verbose_name='タグ')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=256)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VideoRecomApp.Post')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
