# Generated by Django 2.2.6 on 2019-12-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoRecomApp', '0003_auto_20191201_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
