# Generated by Django 2.2.6 on 2019-12-01 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VideoRecomApp', '0005_commentlike_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoRecomApp.Comment'),
        ),
    ]
