# Generated by Django 2.2.6 on 2019-12-01 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VideoRecomApp', '0006_auto_20191201_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoRecomApp.Movie')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movielike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
