# Generated by Django 2.2.6 on 2020-01-05 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('content', models.CharField(max_length=1000, verbose_name='内容')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('favourites', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '短评',
                'verbose_name_plural': '短评',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='类别')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='打分日期')),
                ('grade', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='打分')),
            ],
            options={
                'verbose_name': '用户打分',
                'verbose_name_plural': '用户打分',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='上映年份')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='评分')),
                ('cover', models.ImageField(upload_to='movies', verbose_name='电影封面')),
                ('link_to_watch', models.URLField(blank=True, null=True, verbose_name='观看地址')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='添加到后台日期')),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
                ('favourites', models.IntegerField(blank=True, default=0)),
                ('watches', models.IntegerField(blank=True, default=0)),
                ('director', models.CharField(max_length=255, verbose_name='导演')),
                ('production_countries', models.CharField(max_length=255, verbose_name='国家或地区')),
                ('key_actors', models.CharField(max_length=255, verbose_name='主演')),
            ],
            options={
                'verbose_name_plural': '电影',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_liked_num', models.IntegerField(default=0, verbose_name='喜欢我的影迷数')),
                ('friends_disliked_num', models.IntegerField(default=0, verbose_name='不喜欢我的影迷数')),
                ('friends_favourite_num', models.IntegerField(default=0, verbose_name='关注我的影迷数')),
            ],
            options={
                'verbose_name': '用户观影档案',
                'verbose_name_plural': '用户观影档案',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(blank=True, max_length=128, null=True, verbose_name='Cover')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('edit_date', models.DateTimeField(auto_now=True, null=True, verbose_name='编辑日期')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('favourites', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '影评',
                'verbose_name_plural': '影评',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
    ]
