# Generated by Django 2.2.6 on 2020-01-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200106_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to='movie.Profile', verbose_name='我')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='movie.Profile', verbose_name='我')),
            ],
            options={
                'verbose_name': '关注的好友',
                'verbose_name_plural': '关注的好友',
                'ordering': ('-date',),
                'unique_together': {('me', 'friend')},
            },
        ),
    ]
