# Generated by Django 2.2.6 on 2020-01-05 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '关注的好友',
                'verbose_name_plural': '关注的好友',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ProfileDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '影迷拍砖',
                'verbose_name_plural': '影迷拍砖',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ProfileLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '影迷点赞',
                'verbose_name_plural': '影迷点赞',
                'ordering': ('-date',),
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disliked_friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favourite_friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends_disliked_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends_favourite_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends_liked_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='liked_friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.AddField(
            model_name='profilelike',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_like', to='movie.Profile', verbose_name='点赞对象'),
        ),
        migrations.AddField(
            model_name='profilelike',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_like', to='movie.Profile', verbose_name='我'),
        ),
        migrations.AddField(
            model_name='profiledislike',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_dislike', to='movie.Profile', verbose_name='拍砖对象'),
        ),
        migrations.AddField(
            model_name='profiledislike',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_dislike', to='movie.Profile', verbose_name='我'),
        ),
        migrations.AddField(
            model_name='friendfavourite',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_favourite', to='movie.Profile', verbose_name='关注对象'),
        ),
        migrations.AddField(
            model_name='friendfavourite',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_favourite', to='movie.Profile', verbose_name='我'),
        ),
        migrations.AlterUniqueTogether(
            name='profilelike',
            unique_together={('me', 'friend')},
        ),
        migrations.AlterUniqueTogether(
            name='profiledislike',
            unique_together={('me', 'friend')},
        ),
        migrations.AlterUniqueTogether(
            name='friendfavourite',
            unique_together={('me', 'friend')},
        ),
    ]
