# Generated by Django 2.2.6 on 2020-01-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
